const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});
 const page = await browser.newPage({viewport:{width:1500,height:1000}});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 try {
  await page.addInitScript(()=>localStorage.setItem('comfy.prompt-library.v2',JSON.stringify({version:2,tags:[{id:'a',name:'Soft light',text:'soft lighting'}],prefixes:[{id:'b',name:'Portrait starter',tags:['a']}]})));
  await page.goto(process.env.GALLERY_QA_URL || 'http://127.0.0.1:8191');
  await page.getByRole('tab',{name:'Gallery workspace',exact:true}).click();
  const checkbox=page.getByRole('checkbox',{name:'Select study-4.png',exact:true});
  await checkbox.waitFor();
  const hit=await checkbox.locator('..').locator('..').boundingBox();assert.ok(hit.width>=34&&hit.height>=34);
  await checkbox.click();
  assert.equal(await checkbox.isChecked(),true);
  assert.equal(await page.getByRole('dialog',{name:/Gallery viewer/}).count(),0);
  await page.getByAltText('study-4.png',{exact:true}).dblclick();
  let viewer=page.getByRole('dialog',{name:/Gallery viewer/});
  await viewer.waitFor();assert.equal(await viewer.getByRole('checkbox',{name:'Selected',exact:true}).isChecked(),true);
  await viewer.getByRole('button',{name:'Close',exact:true}).click();
  await page.getByAltText('study-3.png',{exact:true}).dblclick();
  await viewer.waitFor();assert.equal(await viewer.getByRole('checkbox',{name:'Selected',exact:true}).isChecked(),false);
  await viewer.getByRole('button',{name:'Close',exact:true}).click();
  await page.getByAltText('study-4.png',{exact:true}).click({button:'right'});
  await page.getByRole('menuitem',{name:'Delete local file(s) (1)',exact:true}).click();
  const confirmation=page.getByRole('dialog',{name:'Delete 1 local file(s)?',exact:true});
  await confirmation.getByRole('button',{name:'Cancel',exact:true}).click();
  assert.equal(await page.locator('[data-gallery-entry]').count(),4);
  const search=page.getByRole('combobox',{name:'Filter local files',exact:true});
  await search.fill('azure');
  await page.getByText('azure sky · positive · 1 local files',{exact:false}).waitFor();
  await search.press('Escape');await search.fill('');await search.blur();
  await page.getByRole('button',{name:'Prompts & prefixes',exact:true}).click();
  const prompts=page.getByRole('dialog',{name:'Prompts & prefixes',exact:true});
  await prompts.getByText('azure sky',{exact:true}).waitFor();
  await prompts.getByRole('combobox',{name:'Prompt vocabulary',exact:true}).press('ArrowDown');
  await page.getByTitle('library',{exact:true}).click();
  await prompts.getByText('Portrait starter',{exact:true}).waitFor();
  await prompts.getByRole('button',{name:'Close',exact:true}).click();
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await page.getByRole('menuitem',{name:'Gallery settings',exact:true}).click();
  const settings=page.getByRole('dialog',{name:'Settings',exact:true});
  await settings.getByRole('button',{name:'Add folder rule',exact:true}).click();
  const terms=settings.getByRole('combobox',{name:'Rule terms 1',exact:true});
  await terms.fill('azure sky');await terms.press('Enter');await terms.press('Escape');
  await settings.getByRole('textbox',{name:'Rule folder 1',exact:true}).fill('landscapes');
  let payload;
  await page.route('**/Gallery/organize',async route=>{payload=route.request().postDataJSON();await route.fulfill({json:{items:[{url:'/static_gallery/study-1.png',target:'output/landscapes/study-1.png'}]}});});
  await settings.getByRole('button',{name:'Preview moves',exact:true}).click();
  await settings.getByText('1 matching files',{exact:true}).waitFor();
  assert.equal(payload.apply,false);assert.deepEqual(payload.rules[0].terms,['azure sky']);
  assert.equal(await settings.getByRole('switch',{name:'Automatically organize local images',exact:true}).isChecked(),false);
  await settings.getByRole('button',{name:'Return',exact:true}).click();
  await page.route('**/Gallery/delete',async route=>{assert.equal(route.request().postDataJSON().root,'./');await route.fulfill({json:{deleted:'/static_gallery/study-4.png'}});});
  await page.getByAltText('study-4.png',{exact:true}).click({button:'right'});
  await page.getByRole('menuitem',{name:'Delete local file(s) (1)',exact:true}).click();
  await confirmation.getByRole('button',{name:'Delete permanently',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('[data-gallery-entry]').length===3);
  // Tiny synthetic VP8/WebM fixture: two solid-colour frames, no external media.
  const clip=require('node:fs').readFileSync(require('node:path').join(__dirname,'fixtures/solid-colours.webm'));
  await page.route('**/static_gallery/qa-video.webm',route=>route.fulfill({body:Buffer.from(clip),contentType:'video/webm'}));
  await page.route('**/Gallery/images*',async route=>{const response=await route.fetch();const data=await response.json();data.folders.output['qa-video.webm']={name:'qa-video.webm',url:'/static_gallery/qa-video.webm',type:'media',timestamp:2000000000,metadata:{}};await route.fulfill({json:data});});
  await page.reload();await page.getByRole('tab',{name:'Gallery workspace',exact:true}).click();
  const video=page.locator('[data-gallery-entry="local:/static_gallery/qa-video.webm"] video');
  await video.waitFor();await video.click();
  viewer=page.getByRole('dialog',{name:/Gallery viewer/});
  await viewer.waitFor();
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('.ant-modal video')).some(video=>video.readyState>=2)).catch(async error=>{console.log('Video QA',clip.length,await page.locator('video').evaluateAll(videos=>videos.map(video=>({src:video.currentSrc,ready:video.readyState,error:video.error?.message}))));throw error;});
  assert.equal(await viewer.locator('video').evaluate(video=>video.controls),true);
  await viewer.getByRole('button',{name:'Close',exact:true}).click();
  await viewer.waitFor({state:'hidden'});
  await page.getByText('Hydrus',{exact:true}).first().click();
  await page.getByRole('button',{name:'Search',exact:true}).click();
  const remote=page.locator('[data-gallery-entry^="hydrus:"]');
  await remote.first().waitFor();
  await page.route('**/Gallery/hydrus/trash',async route=>{const body=route.request().postDataJSON();assert.ok(body.target.endsWith('|main'));await route.fulfill({json:{trashed:body.hashes}});});
  await remote.first().click({button:'right'});
  await page.getByRole('menuitem',{name:'Delete from Hydrus — send to trash (1)',exact:true}).click();
  await page.getByRole('button',{name:'Send to Hydrus trash',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('[data-gallery-entry^="hydrus:"]').length===3);
  assert.deepEqual(errors,[]);
  if(process.env.GALLERY_QA_SCREENSHOT) await page.screenshot({path:process.env.GALLERY_QA_SCREENSHOT});
  console.log('PASS: large checkbox, selection mode single/double click, viewer selection, local delete cancel/apply, Hydrus trash, indexed prompt suggestions, shared prefix library, routing preview and WebM playback.');
 } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
